### PR TITLE
Avoid returning None in Set.getComponentTagMap.

### PR DESCRIPTION
**Pull request by andreif**
Return empty TagMap as a fallback.

Related to cannatag/ldap3#255

### CODE REVIEW

**Comment by andreif** [comment]
I guess similar could be done also in `SetOf` but I have no case for testing this at the moment.

**Comment by etingof** [comment]
Hey, thank you for the PR!

It looks to me that those `get*TagMap()` methods are designed to return `None` to indicate an absence of data. If we make them returning empty `TagMap` object, the callers may start failing because they expect and handle `None` or non-empty map. 

That observation makes me think that the problem is actually in `NamedTypes.getTagMap()` which does not handle possible `None`.

Thoughts?

**Comment by etingof** [comment]
@andreif Could you please test [this branch](https://github.com/etingof/pyasn1/pull/13) with your code?

I'd appreciate if you could add a test case as I could not come up with a good one off the top of my head.

**Comment by andreif** [comment]
Closed in favour #13

**Pull request closed without merging**
