### PR TITLE
Drop support for EOL Pythons

### PR DESCRIPTION
**Pull request by jdufresne**
Python 2.4, 2.5, 2.6, 3.2 and 3.3 are end of life. They are no longer receiving bug fixes, including for security issues. These Pythons went EOL on:

Python 2.6: 2013-10-29
Python 3.2: 2016-02-20
Python 3.3: 2017-09-29

For additional details on supported Python versions, see:

https://devguide.python.org/#status-of-python-branches

Removing support for EOL Pythons will reduce testing and maintenance resources.

Using [pypinfo](https://github.com/ofek/pypinfo), here are the download statistics of the project for the last 30 days, showing limited downloads from EOL Pythons:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  90.33% |      7,975,885 |
| 3.6            |   4.95% |        437,261 |
| 3.5            |   2.99% |        263,637 |
| 3.4            |   1.02% |         89,723 |
| 2.6            |   0.69% |         60,511 |
| 3.7            |   0.02% |          2,024 |
| 3.3            |   0.00% |            441 |
| 3.2            |   0.00% |             38 |
| 3.8            |   0.00% |              9 |
| None           |   0.00% |              2 |

By removing support for older Pythons, can remove or update the following workarounds and code:

* Built-in function `bin()` is always available.
* Built-in function `callable()` is always available.
* Built-in function `all()` is always available.
* The `collections.OrderedDict` class is always available.
* The `datetime.strptime()` method is always available.
* The `platform` module is always available.
* The `string.partition()` method is always available.
* The `NullHandler` class is always available.
* The method `__trunc__` is always available.
* Can use set literals.
* Updated `unittest` is always available. The `unittest2` module is unnecessary.

Users on older versions of Python can continue to download, install, and use older versions of the library that continue to have support for older Pythons.

### CODE REVIEW

**Comment by jdufresne** [comment]
I have rebased to resolve merge conflicts.

**Comment by etingof** [comment]
Thank you for the patch!

I generally agree with your proposal to drop legacy stuff from master and probably keep supporting
current code to some degree in a branch.

My only concern is if we should drop 2.6 support right away? Would it burden us and clog the code if we keep master compatible with 2.6 at the time being?

WDYT?

**Comment by jdufresne** [comment]
Python 2.6 has been EOL since 2013-10-29, nearly five years. IMO, that is sufficient time for projects to migrate to a newer Python that plan to. Those projects that do not wish to migrate migrate, they can continue to pip install an older version of pyasn1. Or, assuming they're using a distro supplied Python, they can also use a distro supplied pyasn1.

Keeping Python 2.6 support will mean that some workarounds will need to be restored, For example, OrderedDict, NullHandler, set literals, and unittest2. So, my preference would be to continue with only currently supported Python versions.

That said, you're the maintainer of the project and am happy to comply with your wishes. If you still prefer to keep 2.6 support, please let me know and I'll restore the necessary workarounds. If that is your decision, I still think dropping all but 2.6 is a worthwhile improvement.

Cheers.

**Comment by jdufresne** [comment]
Sounds fine to me. Thanks!

**Comment by jdufresne** [comment]
I have rebased and resolved merge conflicts :slightly_smiling_face:

**Comment by etingof** [comment]
Thank you and sorry again for long delay!

**Comment by hugovk** [comment]
Please see https://github.com/etingof/pyasn1/pull/182 to add 3.8 and remove EOL 3.4.

**Pull request merged**
