### PR TITLE
Add method equivalent of x[component]=None

### PR DESCRIPTION
**Pull request by viraptor**
Add a new method which allows setting a default value to a component.
The following lines are equivalent:

   x.setComponentToDefault(comp)
   x[comp] = None

but the first one is more explicit and raises fewer eyebrows during
code review.

### CODE REVIEW

**Comment by etingof** [comment]
I'm struggling with this MR for some time already, so I have a few concerns to discuss:

* We already have .setComponentByPosition() that works exactly the same as .setComponentToDefault() (since it has value defaulted to None). Do we need both?
* For mapping types there is also .setComponentByName() and .setComponentByType() methods, should they have counterparts like .setComponentByNameToDefault() for API consistency? On the other hand that makes API even more hairy.
* To set all defaulted components to their defaults all at once we can use .setDefaultComponents(). But that would not touch non-defaulted components of mapping types and would not grow sequences (like *seq[10] = None* adds 10 elements to a sequence and initialize them with a pyasn1 type). We could probably invent a method like .populateStructureWithElements(start, stop) which is very close to what you have proposed.

I absolutely hate the *comp[key] = None* way of initializing things, however I'm having troubles coming up with a much better API call. Here None is a sentinel, would it make things more clear if we would have  a more explicit and dedicated sentinel like *comp[key] = defaultValue* or pass it to a callable like *setDefault(comp[key])*...?

What do you think would be the most logical, convenient and concise API? I appreciate your thoughts and feedback!

**Comment by viraptor** [comment]
I considered `.setComponentByPosition()` before, but find it just as surprising as `= None`. The reason in both cases is that the code like:
```
x.setComponentByPosition('foo', None)
x['foo']['bar'] = y
```
and
```
x['foo'] = None
x['foo']['bar'] = y
```
raise the same question: "You just set it to None, it's going to explode at runtime, right?"

`.setComponentToDefault()` may be doing exactly the same thing under the covers, but is more explicit. Even without ever seeing pyasn1 interface before, a random developer will figure out what's going on in:
```
x.setComponentToDefault('foo')
x['foo']['bar'] = 1
```
(this is not theoretical situation by the way, I develop code for openstack which is publicly reviewed and got that question a few times)

I admit, I haven't seen `.setComponentByType()` before, and it is tricky. But then again, I don't know if it matters much in this case. If you're selecting the component by type, you need the complete type already. Which means you're just one step from getting your own default anyway.
The problem with hand-crafting the named default is that I need to get the tags from the component description, but when setting by type I must already have them. Unless I'm missing something it's essentially:
```
t = create_some_type_in_potentially_long_way
x.setComponentByType(t.getTagSet(), t)
```
Which doesn't include `None` and is already quick and clear.

Regarding the third point, I have no opinion. Is the mass-initialisation popular? It seems like if you wanted more than one default object, you'd customise them afterwards, so it's not a huge difference to initialise each element before customisation. But maybe other people have a use for it?...

I like both the defaultvalue alternatives. Although in the assigning case, I'd prefer:
```
x['foo'] = make_default_value()
```
so that it's clear that it's a different value each time (even if internally you do always return the same static sentinel (which actually makes a lot of sense)).

**Comment by viraptor** [comment]
Actually I realised that `setDefault(x['foo'])` won't work - it would be `setDefault(None)`. Then again `setDefault(x, 'foo')` would work for types too - `setDefault(x, t.getTagSet())`, just needs to check for string/integer/tagset argument.

But... it would stick out badly in the whole design - everything else is very OOPy, but this would be a completely separate method.

So I guess I like the default sentinel the best. I'm happy to implement that if you agree. Or look at other ideas if not.

**Comment by etingof** [comment]
As far as I know, mass initialization is not popular. The use case I'm aware of behind:

    x['foo'] = None

is to be able to do:

    x['foo']['bar'] = 123

To be more precise, the above does not actually set a default value. Rather, when we do *x['foo'] = None*, we ask *x* to take pyasn1 object that is associated with *'foo'* (through *componentType = NamedTypes()*) and set it as a value object for *x['foo']*. If that type object does not have a default (*Integer(1)* vs *Integer()*), then you still could not read from *x['foo']* (*i = x['foo']* would fail unless type for *foo* is defined with default *Integer(1)*) but you can go on with further initialization.  Here I'm talking of a scalar component type for simplicity, initialization does not make much sense for scalars.

While I generally prefer the explicit sentinel/function solution over explicit .setComponentToDefault(), the alternative idea would be to permit reading from an unset component, so that:

    x['foo']['bar'] = 123
    
would automatically initialize *x['foo']* on component miss prior to performing *x['foo']['bar']* assignment. That change would propagate deep into AbstractConstructedAsn1Item. For instance:

    x.getComponentByPosition(123)  # -> None
    x.setComponentByPosition(123)  # -> initialize component 123 
    x.setComponentByPosition(123, 'foo')  # -> initialize component 123 and set value 'foo' into it

would turn into:

    x.getComponentByPosition(123)  # -> initialize component 123
    x.setComponentByPosition(123)  # -> initialize component 123
    x.setComponentByPosition(123, 'foo')  # -> initialize component 123 and set value 'foo' into it

On the other hand, assigning to [uninitialized] inner components of a dictionary-like object *x['foo']* may look more surprising than *x['foo'] = set_value_object_for_component(); x['foo']['bar'] = 123*, no?

**Comment by viraptor** [comment]
So basically perl's autovivification? Not a huge fan, but also I'm worried about any existing codebase. If you go that way, then any case of:

    if not x['foo']: ...
    if x['foo'] is None: ...

starts failing. I've got a number of those even in a tiny project, so I'm sure other people will be upset too. Even if it could be done with some false'y placeholders so that real setting is delayed, the `is None` comparisons will fail anyway :(

**Comment by etingof** [comment]
I agree, implicit vivification is evil. BTW, defaultdict in Python can do similar things.
Unless you get better ideas, I'd stick to a function returning a sentinel value (we would probably want to retain current behavior (e.g. x['foo'] = None) for backward compatibility).
If you implement that, I'd be happy to merge your implementation.
Thank you for a great debate!

**Comment by viraptor** [comment]
A bit more code for this one, hope this one is good enough :)

**Comment by etingof** [comment]
One more question: would it make sense to use *base.noValue* object as a sentinel? Like this:

    x.setComponentByPosition(0, noValue)
    x['foo'] = noValue

To hint users that *noValue* is not a constant (which it is), we could make it callable (and returning self):

    x.setComponentByPosition(0, noValue())
    x['foo'] = noValue()

My concerns are:

* We are adding an arguably duplicate entity (noValue vs DEFAULT_VALUE_SENTINEL)
* We do not really want to set **default value**, but we want to set a "wireframe" object that could be populated afterwards (the whole concept of pyasn1 object being either an ASN.1 type or  ASN.1 type  instance is confusing). In that regards may be noValue is more obvious?

What do you think?

Sorry for being so nitpicking - I'm trying to make the whole thing less obscure to users... ;-\

**Comment by viraptor** [comment]
Does this have the same result though? I'm thinking about something like:
```
Inner ::= SEQUENCE {
    ... }
Outer  ::=  SEQUENCE  {
    ... ,
    inner [1] Inner OPTIONAL  }
```
wouldn't `outer['inner'] = noValue` result in actually setting no value on that component, rather than an empty `Inner`?

**Comment by etingof** [comment]
Currently, instantiating pyasn1 **scalar** class with noValue makes it "ASN.1 type" meaning that such object can't participate in operations other than creating "ASN.1 type instances".

    asn1_type_object = Integer(noValue)
    asn1_type_object += 1                  # -> failure
    asn1_type_instance_object = asn1_type_object.clone(123)
    asn1_type_instance_object += 1  # -> 124

So if component has associated scalar type:

    outer['scalar_foo'] = 123           # -> sets ASN.1 type instance object for component
    outer['scalar_foo'] = noValue    # -> sets ASN.1 type object for component

you end up with *foo* being ASN.1 type after setting it to *noValue*.

However, if inner component is a constructed ASN.1 type, current implementation won't let you assigning noValue to it. But it accepts None sentinel to create a single (non-recursive) inner ASN.1 type object.

    outer['constructed_foo'] = None      # -> sets ASN.1 type object for component
    outer['constructed_foo'] = noValue  # -> currently, failure

 So I propose to unify this and use noValue sentinel for both scalar and constructed types.

    outer['constructed_foo'] = None      # -> sets ASN.1 type object for component ( would be legacy)
    outer['constructed_foo'] = noValue  # -> sets ASN.1 type object for component

Does it make sense?

**Comment by etingof** [comment]
I've implemented the above approach in [https://github.com/etingof/pyasn1/commit/fa78f1b0b3cd8c9628f8862ce1c19b7597a08be6](https://github.com/etingof/pyasn1/commit/fa78f1b0b3cd8c9628f8862ce1c19b7597a08be6).

I'd appreciate your feedback! Thanks!

**Pull request closed without merging**
